import Link from "next/link";
import { ArrowRight, Clock3, MapPin, Users, X } from "lucide-react";
import { Badge } from "../common/Badge";
import { Card } from "../common/Card";

export function BusDetailsPanel({ bus, onClose }) {
  if (!bus) return null;
  return <Card className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--primary)]">{bus.route || "Live vehicle"}</p><h2 className="mt-1 text-lg font-bold text-[var(--foreground)]">{bus.number || bus.busNumber || bus.name || "Bus details"}</h2><p className="mt-1 text-sm text-[var(--muted)]">{bus.routeName || "Transit route"}</p>{bus.directionLabel && <p className="mt-1 text-sm font-semibold text-[var(--foreground)]">{bus.directionLabel}</p>}</div><button type="button" className="grid h-8 w-8 place-items-center rounded-lg text-[var(--muted)] hover:bg-[#eef7f3] hover:text-[var(--foreground)]" onClick={onClose} aria-label="Close bus details"><X size={17} /></button></div><div className="mt-4 flex flex-wrap gap-2"><Badge tone={bus.status === "Delayed" ? "warning" : bus.status === "Arriving" ? "neutral" : "success"}>{bus.status || "In service"}</Badge></div><div className="mt-4 grid gap-3 border-t border-[var(--border)] pt-4 text-sm"><div className="flex items-center justify-between gap-3"><span className="inline-flex items-center gap-2 text-[var(--muted)]"><Clock3 size={15} /> ETA</span><strong className="text-[var(--foreground)]">{bus.eta || "Updating"}</strong></div><div className="flex items-center justify-between gap-3"><span className="inline-flex items-center gap-2 text-[var(--muted)]"><MapPin size={15} /> Next stop</span><strong className="max-w-[58%] truncate text-right text-[var(--foreground)]">{bus.nextStop || "Updating"}</strong></div><div className="flex items-center justify-between gap-3"><span className="inline-flex items-center gap-2 text-[var(--muted)]"><Users size={15} /> Seats</span><Badge tone={bus.occupancy === "Full" ? "danger" : bus.occupancy === "Limited" ? "warning" : "success"}>{bus.occupancy || "Updating"}</Badge></div></div><Link href={`/buses/${bus.id || bus.busId || bus.number}`} className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-[var(--primary)] hover:text-[var(--primary-dark)]">View bus details <ArrowRight size={15} /></Link></Card>;
}
