"use client";

import Link from "next/link";
import { ArrowRight, Clock3, MapPin, Navigation, Users, X } from "lucide-react";
import { Badge } from "../common/Badge";
import { Button } from "../common/Button";
import { Card } from "../common/Card";

export function BusDetailsPanel({ bus, stops = [], onClose, followActive, onToggleFollow, stale = false, offline = false, cachedAt }) {
  if (!bus) return null;
  const operating = bus.status === "active" || bus.status === "Active" || ["On Time", "Delayed", "Arriving"].includes(bus.status);
  const nextIndex = stops.findIndex((stop) => String(stop._id || stop.id) === String(bus.nextStopId));
  const lookAhead = nextIndex >= 0 ? stops.slice(Math.max(0, nextIndex - 1), nextIndex + 3) : [];
  return <Card className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--primary-ink)]">{bus.routeName || bus.route || "Transit route"}</p><h2 className="mt-1 text-lg font-bold text-[var(--foreground)]">{bus.number || bus.busNumber || "Bus details"}</h2>{bus.directionLabel && <p className="mt-1 text-sm font-semibold text-[var(--foreground)]">{bus.directionLabel}</p>}</div><button type="button" className="grid h-8 w-8 place-items-center rounded-lg text-[var(--muted)] hover:bg-[var(--primary-soft)]" onClick={onClose} aria-label="Close bus details"><X size={17} /></button></div><div className="mt-4"><Badge tone={offline || stale || !operating ? "warning" : "success"}>{offline ? "Offline data" : stale ? "Location update delayed" : operating ? "Currently operating" : "Not operating"}</Badge></div>{offline ? <p className="mt-4 border-t border-[var(--border)] pt-4 text-sm text-[var(--muted)]">Last known location{cachedAt ? ` · Updated ${new Date(cachedAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}` : ""}. Live tracking and arrival times will resume when you are back online.</p> : operating && !stale ? <><div className="mt-4 grid gap-3 border-t border-[var(--border)] pt-4 text-sm"><Row icon={Clock3} label={bus.terminalReached ? "Service" : "Arriving in"} value={bus.terminalReached ? "Approaching terminal" : bus.eta} /><Row icon={MapPin} label="Next stop" value={bus.nextStop} /><Row icon={Users} label="Seats" value={bus.occupancy || (bus.availableSeats != null ? `${bus.availableSeats} available` : null)} /></div>{lookAhead.length > 1 && <ol className="mt-4 grid gap-1 border-t border-[var(--border)] pt-3 text-xs text-[var(--muted)]">{lookAhead.map((stop, index) => <li key={stop.routeStopId || stop._id || stop.id} className={index === 1 ? "font-bold text-[var(--primary-ink)]" : ""}>{index === 0 ? "Current: " : index === 1 ? "Next: " : "Then: "}{stop.stopName || stop.name}</li>)}</ol>}</> : <p className="mt-4 border-t border-[var(--border)] pt-4 text-sm text-[var(--muted)]">{stale ? "Live arrival details are paused until a fresh location update arrives." : "This bus is not currently running a live trip."}</p>}{onToggleFollow && <Button type="button" variant={followActive ? "secondary" : "primary"} className="mt-4 min-h-10 w-full gap-2" onClick={onToggleFollow} disabled={!operating || stale || offline}><Navigation size={15} />{followActive ? "Stop following bus" : "Follow bus"}</Button>}<Link href={`/buses/${bus.id || bus.busId || bus._id}`} className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-[var(--primary-ink)]">View bus details <ArrowRight size={15} /></Link></Card>;
}

function Row({ icon: Icon, label, value }) { return <div className="flex items-center justify-between gap-3"><span className="inline-flex items-center gap-2 text-[var(--muted)]"><Icon size={15} /> {label}</span><strong className="live-transit-value max-w-[58%] truncate text-right">{value || "Unavailable"}</strong></div>; }
